import type { Tailor } from './tailors.types';

export const TAILOR_FIXTURES: Tailor[] = [
  {
    _id: 't1', slug: 'usman-khan',
    userId: { _id: 'u1', name: 'Usman Khan' },
    tier: 'master',
    serviceAreas: [{ city: 'Lahore', area: 'Gulberg' }, { city: 'Lahore', area: 'DHA' }],
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 2500 },
      { garmentCategoryId: 'gc7', garmentCategorySlug: 'suit', price: 4500 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 15000 },
    ],
    specialisations: ['Shalwar Kameez', 'Bridal', 'Suit'],
    rating: 4.9, reviewCount: 312, completedOrders: 847,
    isAvailable: true,
    portfolio: [
      { imageUrl: '', caption: 'Custom Sherwani' },
      { imageUrl: '', caption: 'Bridal Lehenga Set' },
      { imageUrl: '', caption: 'Formal Shalwar Kameez' },
      { imageUrl: '', caption: 'Embroidered Kurta' },
    ],
  },
  {
    _id: 't2', slug: 'ayesha-bibi',
    userId: { _id: 'u2', name: 'Ayesha Bibi' },
    tier: 'premium',
    serviceAreas: [{ city: 'Karachi', area: 'Clifton' }, { city: 'Karachi', area: 'Defence' }],
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 1800 },
      { garmentCategoryId: 'gc1', garmentCategorySlug: 'frock', price: 2200 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 12000 },
    ],
    specialisations: ['Bridal', 'Shalwar Kameez', 'Kids'],
    rating: 4.7, reviewCount: 189, completedOrders: 423,
    isAvailable: true,
    portfolio: [
      { imageUrl: '', caption: 'Anarkali Frock' },
      { imageUrl: '', caption: 'Kids Party Dress' },
      { imageUrl: '', caption: 'Bridal Lehnga' },
      { imageUrl: '', caption: 'Co-ord Set' },
    ],
  },
  {
    _id: 't3', slug: 'rashid-darzi',
    userId: { _id: 'u3', name: 'Rashid Darzi' },
    tier: 'premium',
    serviceAreas: [{ city: 'Islamabad', area: 'F-7' }, { city: 'Rawalpindi', area: 'Saddar' }],
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 2000 },
      { garmentCategoryId: 'gc7', garmentCategorySlug: 'suit', price: 3500 },
    ],
    specialisations: ['Suit', 'Western', 'Uniform'],
    rating: 4.8, reviewCount: 245, completedOrders: 601,
    isAvailable: false,
    portfolio: [
      { imageUrl: '', caption: '3-Piece Suit' },
      { imageUrl: '', caption: 'Office Uniform' },
      { imageUrl: '', caption: 'Formal Shalwar Kameez' },
    ],
  },
  {
    _id: 't4', slug: 'fatima-darzi',
    userId: { _id: 'u4', name: 'Fatima Darzi' },
    tier: 'standard',
    serviceAreas: [{ city: 'Faisalabad', area: 'D-Ground' }],
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 1200 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 8000 },
    ],
    specialisations: ['Shalwar Kameez', 'Bridal'],
    rating: 4.3, reviewCount: 78, completedOrders: 156,
    isAvailable: true,
    portfolio: [
      { imageUrl: '', caption: 'Everyday Lawn Set' },
      { imageUrl: '', caption: 'Bridal Set' },
    ],
  },
  {
    _id: 't5', slug: 'hassan-tailor',
    userId: { _id: 'u5', name: 'Hassan Tailor' },
    tier: 'master',
    serviceAreas: [{ city: 'Lahore', area: 'Anarkali' }, { city: 'Lahore', area: 'Liberty' }],
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 3000 },
      { garmentCategoryId: 'gc7', garmentCategorySlug: 'suit', price: 6000 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 20000 },
    ],
    specialisations: ['Bridal', 'Suit', 'Shalwar Kameez', 'Western'],
    rating: 5.0, reviewCount: 421, completedOrders: 1102,
    isAvailable: true,
    portfolio: [
      { imageUrl: '', caption: 'Luxury Sherwani' },
      { imageUrl: '', caption: 'Bridal Gharara' },
      { imageUrl: '', caption: 'Wedding Suit' },
      { imageUrl: '', caption: 'Embroidered Lehenga' },
    ],
  },
  {
    _id: 't6', slug: 'zara-stitching',
    userId: { _id: 'u6', name: 'Zara Stitching' },
    tier: 'standard',
    serviceAreas: [{ city: 'Multan', area: 'Cantt' }],
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 1000 },
      { garmentCategoryId: 'gc1', garmentCategorySlug: 'frock', price: 1400 },
    ],
    specialisations: ['Shalwar Kameez', 'Kids'],
    rating: 4.1, reviewCount: 34, completedOrders: 89,
    isAvailable: false,
    portfolio: [
      { imageUrl: '', caption: 'Kids Eid Dress' },
      { imageUrl: '', caption: 'Casual Lawn Set' },
    ],
  },
];
