import type { Tailor } from './tailors.types';

export const TAILOR_FIXTURES: Tailor[] = [
  {
    _id: 't1', slug: 'usman-khan',
    userId: { name: 'Usman Khan' },
    tier: 'master',
    serviceAreas: [{ city: 'Lahore', area: 'Gulberg' }, { city: 'Lahore', area: 'DHA' }],
    pricing: { shalwarKameez: 2500, suit: 4500, bridal: 15000 },
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 2500 },
      { garmentCategoryId: 'gc7', garmentCategorySlug: 'suit', price: 4500 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 15000 },
    ],
    specialisations: ['Shalwar Kameez', 'Bridal', 'Suit'],
    rating: 4.9, reviewCount: 312, completedOrders: 847,
    isAvailable: true,
    initials: 'UK', avatarColor: '#1A6B3C',
    portfolio: [
      { imageUrl: '', caption: 'Custom Sherwani', imageColor: '#6D28D9' },
      { imageUrl: '', caption: 'Bridal Lehenga Set', imageColor: '#E879A0' },
      { imageUrl: '', caption: 'Formal Shalwar Kameez', imageColor: '#3B82F6' },
      { imageUrl: '', caption: 'Embroidered Kurta', imageColor: '#F59E0B' },
    ],
  },
  {
    _id: 't2', slug: 'ayesha-bibi',
    userId: { name: 'Ayesha Bibi' },
    tier: 'premium',
    serviceAreas: [{ city: 'Karachi', area: 'Clifton' }, { city: 'Karachi', area: 'Defence' }],
    pricing: { shalwarKameez: 1800, bridal: 12000 },
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 1800 },
      { garmentCategoryId: 'gc1', garmentCategorySlug: 'frock', price: 2200 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 12000 },
    ],
    specialisations: ['Bridal', 'Shalwar Kameez', 'Kids'],
    rating: 4.7, reviewCount: 189, completedOrders: 423,
    isAvailable: true,
    initials: 'AB', avatarColor: '#6D28D9',
    portfolio: [
      { imageUrl: '', caption: 'Anarkali Frock', imageColor: '#E879A0' },
      { imageUrl: '', caption: 'Kids Party Dress', imageColor: '#F9A8D4' },
      { imageUrl: '', caption: 'Bridal Lehnga', imageColor: '#F59E0B' },
      { imageUrl: '', caption: 'Co-ord Set', imageColor: '#FB923C' },
    ],
  },
  {
    _id: 't3', slug: 'rashid-darzi',
    userId: { name: 'Rashid Darzi' },
    tier: 'premium',
    serviceAreas: [{ city: 'Islamabad', area: 'F-7' }, { city: 'Rawalpindi', area: 'Saddar' }],
    pricing: { shalwarKameez: 2000, suit: 3500 },
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 2000 },
      { garmentCategoryId: 'gc7', garmentCategorySlug: 'suit', price: 3500 },
    ],
    specialisations: ['Suit', 'Western', 'Uniform'],
    rating: 4.8, reviewCount: 245, completedOrders: 601,
    isAvailable: false,
    initials: 'RD', avatarColor: '#1E4FCC',
    portfolio: [
      { imageUrl: '', caption: '3-Piece Suit', imageColor: '#1E3A5F' },
      { imageUrl: '', caption: 'Office Uniform', imageColor: '#334155' },
      { imageUrl: '', caption: 'Formal Shalwar Kameez', imageColor: '#5B4A3F' },
    ],
  },
  {
    _id: 't4', slug: 'fatima-darzi',
    userId: { name: 'Fatima Darzi' },
    tier: 'standard',
    serviceAreas: [{ city: 'Faisalabad', area: 'D-Ground' }],
    pricing: { shalwarKameez: 1200, bridal: 8000 },
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 1200 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 8000 },
    ],
    specialisations: ['Shalwar Kameez', 'Bridal'],
    rating: 4.3, reviewCount: 78, completedOrders: 156,
    isAvailable: true,
    initials: 'FD', avatarColor: '#BE185D',
    portfolio: [
      { imageUrl: '', caption: 'Everyday Lawn Set', imageColor: '#86EFAC' },
      { imageUrl: '', caption: 'Bridal Set', imageColor: '#C084FC' },
    ],
  },
  {
    _id: 't5', slug: 'hassan-tailor',
    userId: { name: 'Hassan Tailor' },
    tier: 'master',
    serviceAreas: [{ city: 'Lahore', area: 'Anarkali' }, { city: 'Lahore', area: 'Liberty' }],
    pricing: { shalwarKameez: 3000, suit: 6000, bridal: 20000 },
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 3000 },
      { garmentCategoryId: 'gc7', garmentCategorySlug: 'suit', price: 6000 },
      { garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga', price: 20000 },
    ],
    specialisations: ['Bridal', 'Suit', 'Shalwar Kameez', 'Western'],
    rating: 5.0, reviewCount: 421, completedOrders: 1102,
    isAvailable: true,
    initials: 'HT', avatarColor: '#B45309',
    portfolio: [
      { imageUrl: '', caption: 'Luxury Sherwani', imageColor: '#6D28D9' },
      { imageUrl: '', caption: 'Bridal Gharara', imageColor: '#E879A0' },
      { imageUrl: '', caption: 'Wedding Suit', imageColor: '#1E3A5F' },
      { imageUrl: '', caption: 'Embroidered Lehenga', imageColor: '#F59E0B' },
    ],
  },
  {
    _id: 't6', slug: 'zara-stitching',
    userId: { name: 'Zara Stitching' },
    tier: 'standard',
    serviceAreas: [{ city: 'Multan', area: 'Cantt' }],
    pricing: { shalwarKameez: 1000 },
    categoryPricing: [
      { garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez', price: 1000 },
      { garmentCategoryId: 'gc1', garmentCategorySlug: 'frock', price: 1400 },
    ],
    specialisations: ['Shalwar Kameez', 'Kids'],
    rating: 4.1, reviewCount: 34, completedOrders: 89,
    isAvailable: false,
    initials: 'ZS', avatarColor: '#0D5C63',
    portfolio: [
      { imageUrl: '', caption: 'Kids Eid Dress', imageColor: '#F9A8D4' },
      { imageUrl: '', caption: 'Casual Lawn Set', imageColor: '#34D399' },
    ],
  },
];
