import type { ShopProduct } from './shop.types';

/**
 * Local fixtures — used as UI fallback when the backend is unreachable.
 * Slugs match the ones in home.fixtures so tapping a card shows real-looking detail data.
 */
export const DUMMY_PRODUCTS: ShopProduct[] = [
  {
    _id: 'f1',
    slug: 'summer-lawn-3-piece',
    title: 'Summer Lawn 3-Piece',
    category: 'lawn',
    pricePerSuit: 3200,
    pricePerMetre: 650,
    rating: 4.8,
    reviewCount: 142,
    isFeatured: true,
    status: 'active',
    stock: 24,
    occasion: ['casual', 'eid'],
    targetGender: 'female',
    colour: 'Mint Green',
    composition: '100% Cotton Lawn',
    fabricWeight: 80,
    careInstructions: 'hand_wash',
    origin: 'Pakistan',
    shopId: {
      _id: 's1',
      name: 'Gulaal Fabrics',
      slug: 'gulaal-fabrics',
      address: { city: 'Lahore' },
      rating: 4.7,
      isVerified: true,
    },
  },
  {
    _id: 'f2',
    slug: 'bridal-silk-embroidered',
    title: 'Bridal Silk Embroidered',
    category: 'bridal',
    pricePerSuit: 8500,
    pricePerMetre: 1800,
    rating: 4.9,
    reviewCount: 89,
    isFeatured: true,
    status: 'active',
    stock: 8,
    occasion: ['bridal', 'formal'],
    targetGender: 'female',
    colour: 'Ivory White',
    composition: '100% Pure Silk',
    fabricWeight: 120,
    careInstructions: 'dry_clean',
    origin: 'Pakistan',
    shopId: {
      _id: 's2',
      name: 'Zara Bridal',
      slug: 'zara-bridal',
      address: { city: 'Karachi' },
      rating: 4.9,
      isVerified: true,
    },
  },
  {
    _id: 'f3',
    slug: 'chiffon-dupatta-set',
    title: 'Chiffon Dupatta Set',
    category: 'chiffon',
    pricePerSuit: 2800,
    pricePerMetre: 560,
    rating: 4.6,
    reviewCount: 74,
    isFeatured: false,
    status: 'active',
    stock: 31,
    occasion: ['casual', 'party'],
    targetGender: 'female',
    colour: 'Dusty Rose',
    composition: '100% Chiffon',
    fabricWeight: 60,
    careInstructions: 'hand_wash',
    origin: 'Pakistan',
    shopId: {
      _id: 's3',
      name: 'Sana Safinaz',
      slug: 'sana-safinaz',
      address: { city: 'Lahore' },
      rating: 4.6,
      isVerified: true,
    },
  },
  {
    _id: 'f4',
    slug: 'velvet-eid-collection',
    title: 'Velvet Eid Collection',
    category: 'velvet',
    pricePerSuit: 5500,
    pricePerMetre: 1100,
    rating: 4.7,
    reviewCount: 103,
    isFeatured: true,
    status: 'active',
    stock: 15,
    occasion: ['eid', 'formal'],
    targetGender: 'female',
    colour: 'Royal Maroon',
    composition: '100% Velvet',
    fabricWeight: 200,
    careInstructions: 'dry_clean',
    origin: 'Pakistan',
    shopId: {
      _id: 's4',
      name: 'Khaadi',
      slug: 'khaadi',
      address: { city: 'Karachi' },
      rating: 4.8,
      isVerified: true,
    },
  },
  {
    _id: 'f5',
    slug: 'karandi-winter-suit',
    title: 'Karandi Winter Suit',
    category: 'karandi',
    pricePerSuit: 4200,
    pricePerMetre: 850,
    rating: 4.5,
    reviewCount: 58,
    isFeatured: false,
    status: 'active',
    stock: 19,
    occasion: ['casual', 'office'],
    targetGender: 'male',
    colour: 'Navy Blue',
    composition: '100% Wool Karandi',
    fabricWeight: 260,
    careInstructions: 'dry_clean',
    origin: 'Pakistan',
    shopId: {
      _id: 's5',
      name: 'J. Junaid Jamshed',
      slug: 'junaid-jamshed',
      address: { city: 'Lahore' },
      rating: 4.5,
      isVerified: true,
    },
  },
  {
    _id: 'f6',
    slug: 'cotton-casual-kurta',
    title: 'Cotton Casual Kurta',
    category: 'cotton',
    pricePerSuit: 1800,
    pricePerMetre: 360,
    rating: 4.4,
    reviewCount: 211,
    isFeatured: false,
    status: 'active',
    stock: 50,
    occasion: ['casual', 'office'],
    targetGender: 'unisex',
    colour: 'Off-White',
    composition: '100% Cotton',
    fabricWeight: 140,
    careInstructions: 'machine_wash',
    origin: 'Pakistan',
    shopId: {
      _id: 's6',
      name: 'Bonanza Satrangi',
      slug: 'bonanza-satrangi',
      address: { city: 'Lahore' },
      rating: 4.4,
      isVerified: false,
    },
  },
  {
    _id: 'f7',
    slug: 'organza-party-wear',
    title: 'Organza Party Wear',
    category: 'organza',
    pricePerSuit: 6200,
    pricePerMetre: 1250,
    rating: 4.8,
    reviewCount: 67,
    isFeatured: true,
    status: 'active',
    stock: 12,
    occasion: ['party', 'formal'],
    targetGender: 'female',
    colour: 'Blush Pink',
    composition: '100% Organza',
    fabricWeight: 70,
    careInstructions: 'dry_clean',
    origin: 'Pakistan',
    shopId: {
      _id: 's7',
      name: 'Asim Jofa',
      slug: 'asim-jofa',
      address: { city: 'Karachi' },
      rating: 4.9,
      isVerified: true,
    },
  },
  {
    _id: 'f8',
    slug: 'linen-summer-suit',
    title: 'Linen Summer Suit',
    category: 'linen',
    pricePerSuit: 2200,
    pricePerMetre: 440,
    rating: 4.3,
    reviewCount: 95,
    isFeatured: false,
    status: 'active',
    stock: 27,
    occasion: ['casual', 'office'],
    targetGender: 'unisex',
    colour: 'Beige',
    composition: '100% Linen',
    fabricWeight: 160,
    careInstructions: 'machine_wash',
    origin: 'Pakistan',
    shopId: {
      _id: 's8',
      name: 'Nishat Linen',
      slug: 'nishat-linen',
      address: { city: 'Lahore' },
      rating: 4.3,
      isVerified: true,
    },
  },
];
