import type { Design } from './designs.types';

export const DESIGN_FIXTURES: Design[] = [
  {
    _id: 'd1', slug: 'anarkali-long-frock',
    title: 'Anarkali Long Frock',
    garmentCategoryId: 'gc1', garmentCategorySlug: 'frock',
    occasion: ['Bridal', 'Eid'], gender: 'Women',
    images: [], isTrending: true,
    tags: ['embroidery', 'floor-length', 'net'],
    requiredMeasurements: ['bust', 'waist', 'length'],
    imageColor: '#E879A0',
  },
  {
    _id: 'd2', slug: 'classic-shalwar-kameez',
    title: 'Classic Shalwar Kameez',
    garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez',
    occasion: ['Casual'], gender: 'Men',
    images: [], isTrending: false,
    tags: ['cotton', 'everyday'],
    requiredMeasurements: ['chest', 'waist', 'length', 'sleeve'],
    imageColor: '#60A5FA',
  },
  {
    _id: 'd3', slug: 'bridal-lehenga',
    title: 'Bridal Lehenga',
    garmentCategoryId: 'gc3', garmentCategorySlug: 'lehenga',
    occasion: ['Bridal'], gender: 'Women',
    images: [], isTrending: true,
    tags: ['zari', 'heavy-embroidery', 'dupatta'],
    requiredMeasurements: ['bust', 'waist', 'hip', 'length'],
    imageColor: '#F59E0B',
  },
  {
    _id: 'd4', slug: 'eid-sharara-set',
    title: 'Eid Sharara Set',
    garmentCategoryId: 'gc4', garmentCategorySlug: 'sharara',
    occasion: ['Eid', 'Party'], gender: 'Women',
    images: [], isTrending: true,
    tags: ['chiffon', 'mirror-work'],
    requiredMeasurements: ['bust', 'waist', 'hip'],
    imageColor: '#A78BFA',
  },
  {
    _id: 'd5', slug: 'office-palazzo-suit',
    title: 'Office Palazzo Suit',
    garmentCategoryId: 'gc5', garmentCategorySlug: 'palazzo',
    occasion: ['Formal'], gender: 'Women',
    images: [], isTrending: false,
    tags: ['linen', 'minimalist'],
    requiredMeasurements: ['bust', 'waist', 'length'],
    imageColor: '#34D399',
  },
  {
    _id: 'd6', slug: 'embroidered-coord-set',
    title: 'Embroidered Co-ord Set',
    garmentCategoryId: 'gc6', garmentCategorySlug: 'co-ord',
    occasion: ['Eid', 'Party'], gender: 'Women',
    images: [], isTrending: false,
    tags: ['gota', 'peplum'],
    requiredMeasurements: ['bust', 'waist', 'hip'],
    imageColor: '#FB923C',
  },
  {
    _id: 'd7', slug: 'casual-kurta-set',
    title: 'Casual Kurta Set',
    garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez',
    occasion: ['Casual'], gender: 'Women',
    images: [], isTrending: false,
    tags: ['lawn', 'printed'],
    requiredMeasurements: ['bust', 'waist', 'length'],
    imageColor: '#86EFAC',
  },
  {
    _id: 'd8', slug: 'sherwani-classic',
    title: 'Classic Sherwani',
    garmentCategoryId: 'gc7', garmentCategorySlug: 'suit',
    occasion: ['Bridal', 'Formal'], gender: 'Men',
    images: [], isTrending: true,
    tags: ['velvet', 'gold-buttons', 'formal'],
    requiredMeasurements: ['chest', 'waist', 'hip', 'length', 'sleeve'],
    imageColor: '#6D28D9',
  },
  {
    _id: 'd9', slug: 'silk-abaya-embroidered',
    title: 'Embroidered Silk Abaya',
    garmentCategoryId: 'gc8', garmentCategorySlug: 'abaya',
    occasion: ['Formal', 'Eid'], gender: 'Women',
    images: [], isTrending: false,
    tags: ['silk', 'modest', 'floor-length'],
    requiredMeasurements: ['bust', 'hip', 'length', 'sleeve'],
    imageColor: '#1E3A5F',
  },
  {
    _id: 'd10', slug: 'kids-eid-frock',
    title: 'Kids Eid Frock',
    garmentCategoryId: 'gc1', garmentCategorySlug: 'frock',
    occasion: ['Eid', 'Party'], gender: 'Kids',
    images: [], isTrending: true,
    tags: ['organza', 'bow', 'puffy'],
    requiredMeasurements: ['age', 'bust', 'length'],
    imageColor: '#F9A8D4',
  },
  {
    _id: 'd11', slug: 'shalwar-kameez-formal',
    title: 'Formal Shalwar Kameez',
    garmentCategoryId: 'gc2', garmentCategorySlug: 'shalwar-kameez',
    occasion: ['Formal', 'Eid'], gender: 'Men',
    images: [], isTrending: false,
    tags: ['khaddar', 'embroidered-collar'],
    requiredMeasurements: ['chest', 'waist', 'length', 'sleeve'],
    imageColor: '#5B4A3F',
  },
  {
    _id: 'd12', slug: 'party-ghagra-choli',
    title: 'Party Ghagra Choli',
    garmentCategoryId: 'gc9', garmentCategorySlug: 'lehenga',
    occasion: ['Party', 'Bridal'], gender: 'Women',
    images: [], isTrending: true,
    tags: ['sequins', 'heavy', 'dupatta'],
    requiredMeasurements: ['bust', 'waist', 'hip', 'length'],
    imageColor: '#C084FC',
  },
];
